export const TODO_ADDED = 'TODO_ADDED';
export const TODO_TOGGLED = 'TODO_TOGGLED';
export const TODO_EDIT_STATE_TOGGLED = 'TODO_EDIT_STATE_OPENED';
export const TODO_EDITED = 'TODO_EDITED';
export const VISIBILITY_FILTER_SET = 'VISIBILITY_FILTER_SET';